note.gorseecode.ru {
	encode zstd gzip

	header {
		Referrer-Policy "strict-origin-when-cross-origin"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "DENY"
	}

	handle /sync* {
		reverse_proxy note-sync:5199
	}

	handle {
		reverse_proxy note-web:8080
	}
}
